{
    'name': 'Random Team Generator',
    'version': '1.0',
    'summary': 'Génère des équipes aléatoires avec un chef d’équipe',
    'category': 'Tools',
    'author': 'Kavola DIBI',
    'website': 'https://coconut.ci',
    'license': 'LGPL-3',
    'depends': ['base', 'contacts', 'portal', 'mail', 'website'],
    'data': [
        'security/res_partner_portal_security.xml',
        'security/ir.model.access.csv',
        'views/res_config_setting.xml',
        #'data/email_template.xml',
        'views/tribe_views.xml',
        'views/prayer_cell_views.xml',
        'data/tribe_type_data.xml',
        'data/prayer_cell_type_data.xml',
        'views/team_views.xml',
        'views/res_partner_views.xml',
        'views/portal_templates.xml',
        'reports/churches.xml',
        'reports/prayer_cell.xml',
        'reports/schools.xml',
        'data/ir_cron.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
